CREATE TABLE users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(100),
  role ENUM('ADMIN','USER') NOT NULL DEFAULT 'USER',
  birthday DATE NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE calendars (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  description TEXT,
  type ENUM('ADMIN_MANAGED','PERSONAL','BIRTHDAY','CUSTOM') NOT NULL DEFAULT 'CUSTOM',
  owner_user_id BIGINT NULL,
  is_default_personal BOOLEAN NOT NULL DEFAULT FALSE,
  is_birthday_calendar BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_cal_owner FOREIGN KEY (owner_user_id) REFERENCES users(id)
);

CREATE TABLE events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  calendar_id BIGINT NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  start_datetime DATETIME NOT NULL,
  end_datetime DATETIME NOT NULL,
  is_all_day BOOLEAN NOT NULL DEFAULT FALSE,
  recurrence ENUM('NONE','YEARLY','MONTHLY','WEEKLY') NOT NULL DEFAULT 'NONE',
  metadata JSON NULL,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_event_calendar FOREIGN KEY (calendar_id) REFERENCES calendars(id),
  CONSTRAINT fk_event_creator FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE calendar_users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  calendar_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  role ENUM('OWNER','EDITOR','VIEWER') NOT NULL DEFAULT 'VIEWER',
  can_share BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT fk_cu_calendar FOREIGN KEY (calendar_id) REFERENCES calendars(id),
  CONSTRAINT fk_cu_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT uc_calendar_user UNIQUE (calendar_id, user_id)
);

